#!/usr/bin/env cwl-runner
# This file was autogenerated using the Workflow Inference Compiler, version 0+unknown
# https://github.com/PolusAI/workflow-inference-compiler
class: CommandLineTool
cwlVersion: v1.0
label: Returns a dictionary of the given arguments as a JSON-encoded string.
doc: Returns a dictionary of the given arguments as a JSON-encoded string.
baseCommand: echo
requirements:
  InlineJavascriptRequirement: {}
inputs:
  config:
    label: A dictionary of the given arguments as a JSON-encoded string.
    doc: A dictionary of the given arguments as a JSON-encoded string.
    type: string
    format: edam:format_2330
    default: '{}'
  nsteps:
    label: The number of timesteps
    doc: The number of timesteps
    type: int
  dt:
    label: The length of each timestep
    doc: The length of each timestep
    type: float
  ref_t:
    label: The nominal temperature
    doc: The nominal temperature
    type: float
  ref_p:
    label: The nominal pressure
    doc: The nominal pressure
    type: float
outputs:
  output_config_string:
    label: A dictionary of the given arguments as a JSON-encoded string.
    doc: A dictionary of the given arguments as a JSON-encoded string.
    type: string
    outputBinding:
      outputEval: "${\n  var config = JSON.parse(inputs.config);\n  if ((\"mdp\" in\
        \ config) === false) {\n    config[\"mdp\"] = {}; // Initialize it\n  }\n\
        \  // TODO: Check for duplicate keys, i.e.\n  // \"Pressure coupling incorrect\
        \ number of values (I need exactly 1)\"\n  config[\"mdp\"][\"nsteps\"] = inputs.nsteps;\n\
        \  config[\"mdp\"][\"dt\"] = inputs.dt;\n  config[\"mdp\"][\"ref-t\"] = inputs[\"\
        ref-t\"]; //Javascript interprets dash as subtract...\n  config[\"mdp\"][\"\
        ref-p\"] = inputs[\"ref-p\"];\n  return JSON.stringify(config);\n}\n"
$namespaces:
  edam: https://edamontology.org/
$schemas:
- https://raw.githubusercontent.com/edamontology/edamontology/master/EDAM_dev.owl
